Path C:\OpenAVRc_Builder\AVR-GCC\bin;C:\OpenAVRc_Builder\AVR-GCC\utils\bin;C:\OpenAVRc_Builder\Python34
make clean
make LCD=ST7920 X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_ST7920.hex
make clean
make LCD=KS108 X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_KS108.hex
make clean
make LCD=ST7565P X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_ST7565P.hex
make clean
make LCD=ST7565R X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_ST7565R.hex
make clean
make LCD=ERC12864FSF X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_ERC12864FSF.hex
make clean
make LCD=SSD1306 X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_SSD1306.hex
make clean
make LCD=SH1106 X_ANY=4 EXT=FRSKY RTCLOCK=YES DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=STICKS OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO GPS=YES MULTIMODULE=YES SPIMODULES=YES CC2500=YES CYRF6936=YES SDCARD=YES
rename OpenAVRC.hex OpenAVRcV3_SH1106.hex
make clean

