Path C:\OpenAVRc_Builder\AVR-GCC\bin;C:\OpenAVRc_Builder\AVR-GCC\utils\bin;C:\OpenAVRc_Builder\Python34
make clean
make LCD=ST7920 DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_ST7920.hex
make clean
make LCD=KS108 DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_KS108.hex
make clean
make LCD=ST7565P DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_ST7565P.hex
make clean
make LCD=ST7565R DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_ST7565R.hex
make clean
make LCD=ERC12864FSF DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_ERC12864FSF.hex
make clean
make LCD=SSD1306 DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_SSD1306.hex
make clean
make LCD=SH1106 DSM2=SERIAL FONT=SQT5 EXTERNALEEPROM=YES NAVIGATION=NO OFFSET_ON_INPUT=YES BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGAMINI TRANSLATIONS=FR TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=NO HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO SDCARD=YES GPS=YES
rename OpenAVRC.hex OpenAVRcV3_SH1106.hex
make clean

