#ifndef PERSONAMES_H_INCLUDED
#define PERSONAMES_H_INCLUDED
#undef TR_PHYS_SWITCHES
#define TR_PHYS_SWITCHES   "SW1""SW2""SW3""SW4""SW5""SW6"
#undef TR_9X_3POS_SWITCHES
#define TR_9X_3POS_SWITCHES "ID0""ID1""ID2"
#undef TR_ROTARY_ENCODERS
#define TR_ROTARY_ENCODERS "EN1\0""EN2\0"
#undef TR_ROTENC_SWITCHES
#define TR_ROTENC_SWITCHES "ES1""ES2"
#endif