#ifndef PERSONAMES_H_INCLUDED
#define PERSONAMES_H_INCLUDED
#undef TR_PHYS_SWITCHES
#define TR_PHYS_SWITCHES   "N  ""L  ""O  ""I  ""G  ""M  "
//#define TR_PHYS_SWITCHES "SWA""SWD""ELE""SWB""GEA""TRN"
#undef TR_9X_3POS_SWITCHES
#define TR_9X_3POS_SWITCHES   "Jup""Jmi""Jdn"
//#define TR_9X_3POS_SWITCHES "ID0""ID1""ID2"
#undef TR_ROTARY_ENCODERS
#define TR_ROTARY_ENCODERS "REa\0""REb\0"
#undef TR_ROTENC_SWITCHES
#define TR_ROTENC_SWITCHES "REa""REb"
#endif
