make FADMIXER=YES FONT=SQT5 BOLD=YES 3POS=POT3 VOICE=WTV20SD PCB=MEGA2560 TRANSLATIONS=FR LCD=KS108 TOGGLETRIM=YES NOANDSECONDE=YES TEMPLATES=YES NAVIGATION=NO HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=YES HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 SDCARD=YES AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO JITTER_FILTER=NO EXT=FRSKY SPLASH=YES
pause

