make clean
make LCD=SSD1306 NAVIGATION=STICKS FADMIXER=YES FONT=SQT5 BOLD=YES 3POS=POT3 VOICE=JQ6500 NOANDSECONDE=YES EXT=FRSKY PCB=MEGA2560 TRANSLATIONS=FR TOGGLETRIM=YES TEMPLATES=YES HELI=YES GVARS=YES GPS=NO EEPROM_PROGRESS_BAR=YES DEFAULT_MODE=2 DBLKEYS=YES CURVES=YES AUTOSWITCH=YES AUTOSOURCE=YES HAPTIC=YES PPM_CENTER_ADJUSTABLE=YES PPM_LIMITS_SYMETRICAL=YES PPM_UNIT=PERCENT_PREC1 SDCARD=YES AUDIO=YES BATTGRAPH=YES HARDWARE_VOLUME=NO JITTER_FILTER=NO SPLASH=YES
pause
DSM2=PPM 
LCD=KS108 
LCD=SSD1306 
LCD=ST7920 