make PCB=MEGA2560 TRANSLATIONS=FR LCD=ST7565P HELI=NO TEMPLATES=NO CURVES=YES SDCARD=YES HAPTIC=NO PPM_CENTER_ADJUSTABLE=YES GVARS=NO AUTOSOURCE=NO AUTOSWITCH=YES DBLKEYS=NO BATTGRAPH=YES EEPROM_PROGRESS_BAR=NO PPM_UNIT=US AUDIO=YES VOICE=YES DEFAULT_MODE=1 NAVIGATION=NO GPS=NO SPLASH=YES EXT=FRSKY
pause
